### ISSUE TITLE
Use with WebKit nightly?

### ISSUE THREAD

**Issue by rjkroege** [simonbs/alfred-safari-tabs-workflow#1]
I had thought that changing 

```
tell application "Safari"
```

to

```
tell application "WebKit"
```

would make your awesome-looking workflow work with the WebKit nightly but alas.

I tried running the AppleScript fragment directly and got

```
error "WebKit got an error: AppleEvent handler failed." number -10000    
```

in the line

```
set tabscount to count of every tab of win
```

Any suggestions?

**Comment by simonbs** [comment]
I'm afraid you can't port it directly. If you want it to work with say, Google Chrome, you would have to take a look at the AppleScript dictionary that Google Chrome offers and use that. It's highly unlikely that the dictionary of Google Chrome matches the one of Safari entirely.
